In [1]:
import os
import csv
import pandas as pd

In [5]:
protein = pd.read_table('/Users/hanruchen/Desktop/BioInfo_LAB/Multi_omics/data/protein_expression/TCGA.LUAD.sampleMap_RPPA_RBN', index_col='Sample_description').transpose()
protein

Sample_description,1433EPSILON,4EBP1,4EBP1PS65,4EBP1PT37T46,53BP1,ACCPS79,ACC1,AKT,AKTPS473,AKTPT308,...,XRCC1,YAP,YAPPS127,YB1,YB1PS102,JNKPT183Y185,PAI1,MTORPS2448,ASNS,EGFR
TCGA-05-4244-01,-0.314052,-0.744900,-0.132869,-0.044139,-0.133464,0.149983,4.688833e-02,-0.018325,-0.651815,-0.860921,...,-0.206040,0.187248,0.111551,-0.260373,1.121700,-0.231418,0.367672,0.399033,-0.320634,0.448377
TCGA-05-4249-01,-0.228332,-0.505673,0.020497,0.202685,-0.352470,-0.450569,-3.609890e-01,0.146645,0.002401,-0.118107,...,-0.241651,0.316690,0.463229,-0.640596,0.490173,0.166870,0.043990,0.244476,-0.728384,0.247686
TCGA-05-4250-01,-0.249319,0.148261,-0.265956,-0.104767,-0.197206,-0.022072,-7.327114e-02,-0.069110,-0.030920,-0.676922,...,-0.331183,0.706991,0.680506,-0.216480,0.836604,0.061998,0.951074,-0.047732,-0.241514,-0.072051
TCGA-05-4384-01,-0.090259,-0.899695,-0.144101,0.214329,-0.033074,-0.093818,-2.390853e-01,0.166664,0.552279,0.021791,...,-0.142273,0.428011,0.608077,-0.778912,0.630016,0.368383,-0.703363,0.301146,-1.357417,0.006701
TCGA-05-4396-01,-0.156043,-0.557716,0.229750,0.453861,0.847321,-0.172030,-1.761436e-01,0.275633,0.021392,-0.500658,...,-0.236620,0.460467,0.953717,0.457445,0.153315,-0.027050,-0.513515,0.190835,-0.116908,0.231943
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-97-7554-01,0.012946,-0.498052,0.043802,-0.829682,-0.830861,-0.605719,-5.512501e-01,-0.518190,-1.352066,-0.695794,...,0.043883,0.729100,0.759115,0.085629,0.392547,0.237255,0.431792,-0.071165,-0.196168,0.240422
TCGA-97-7937-01,-0.237792,-0.392091,-0.013356,0.135645,-0.338357,-0.263990,-3.995463e-07,0.070268,-0.300664,-0.396108,...,-0.010162,0.824242,1.177641,-0.141456,0.198226,0.175694,0.766172,-0.024719,0.079982,0.181981
TCGA-97-7938-01,-0.197293,-0.654387,-0.424813,-0.545485,-0.403894,-0.497159,-6.089042e-01,-0.229808,-0.156696,-0.091583,...,-0.368296,1.280876,1.384509,-0.385504,0.299774,0.274604,0.083522,0.083583,-0.841956,0.222525
TCGA-97-7941-01,-0.273052,-0.480249,-0.470146,0.137247,-0.222954,-1.015206,-1.073965e+00,-0.190389,0.220352,-0.166311,...,-0.299453,0.763275,1.143855,-0.294592,0.350467,0.084615,0.158449,0.115251,-1.038563,-0.014592
TCGA-99-7458-01,0.089000,-0.104107,0.295294,0.647482,-0.161756,-0.860220,-7.341095e-01,-0.515908,-0.685400,-0.725152,...,0.057701,0.684560,0.796042,-0.282026,0.575012,0.289480,-0.062834,0.381836,-0.573415,0.141153

In [15]:
protein.loc['TCGA-97-7937-01'][['ACC1', 'YAP']].tolist()

[-3.99546283946783e-07, 0.824242230191252]

In [17]:
gene = pd.read_table('/Users/hanruchen/Desktop/BioInfo_LAB/Multi_omics/data/gene_expression/TCGA.LUAD.sampleMap_HiSeqV2_PANCAN', index_col='sample').transpose()
gene

sample,ARHGEF10L,HIF3A,RNF17,RNF10,RNF11,RNF13,GTF2IP1,REM1,MTVR2,RTN4RL2,...,TULP2,NPY5R,GNGT2,GNGT1,TULP3,PTRF,BCL6B,GSTK1,SELP,SELS
TCGA-69-7978-01,0.125808,-1.294926,-0.112935,-1.411872,0.203922,0.09939,-0.222094,0.504354,-0.423399,2.895028,...,1.134722,-0.845117,1.760167,-1.28139,0.224623,0.863614,0.802173,0.108205,0.595367,-0.222712
TCGA-62-8399-01,0.561708,6.069174,-0.531035,-0.228672,0.052122,-1.20601,-0.338894,1.449854,0.039401,0.274628,...,-0.286078,-0.055517,-0.028233,0.04801,0.295223,0.317114,1.079073,-0.782695,3.114267,-0.388912
TCGA-78-7539-01,-0.237592,3.581474,0.592065,-0.108372,-0.499978,-0.02541,0.163006,0.131654,-0.050899,-1.770772,...,2.209922,-1.587117,1.565367,2.63871,0.049123,-1.243086,-1.283227,0.034105,0.571467,0.233588
TCGA-50-5931-11,-1.180492,3.927674,0.291065,-0.043472,0.710822,1.05089,-0.564394,1.683954,0.398701,-1.954472,...,-0.748878,0.900483,1.903567,-1.28139,-0.549277,2.802714,2.250473,-0.540795,3.985967,0.370988
TCGA-73-4658-01,-0.656192,-0.525926,-0.531035,-0.156672,0.373522,0.44729,-0.438994,1.831554,-0.423399,2.108328,...,-0.748878,-0.931417,1.915167,-0.17659,0.042323,1.110714,1.513973,-0.454095,2.893167,0.193788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-55-7727-01,-2.621192,1.986874,0.408165,0.091028,0.318322,0.16679,0.143706,-1.370846,-0.423399,-0.218672,...,-0.748878,-0.647917,1.158367,1.77851,0.555323,-1.495486,-0.359227,-0.584495,1.663867,0.188988
TCGA-91-6831-01,-1.025192,-1.993426,-0.531035,0.492828,0.150822,-0.53401,-1.071294,-0.701346,-0.423399,2.515128,...,0.076322,-1.587117,-0.369733,0.44771,0.319623,0.472314,0.332973,-1.756895,-0.275933,0.732388
TCGA-MN-A4N4-01,0.070108,2.790974,0.440465,0.037428,-0.357778,-0.32071,-1.039394,1.124154,-0.423399,3.996128,...,2.952822,-1.587117,0.024967,1.66841,0.566123,0.993014,0.570873,0.506805,-0.073933,-0.243412
TCGA-55-8302-01,0.305608,-0.018326,-0.531035,0.003728,-0.451578,-0.38671,-0.084494,-0.217746,-0.423399,-0.706872,...,-0.748878,-1.587117,1.078867,-1.28139,0.280623,0.634014,-0.909527,-0.114895,0.848867,0.195588
TCGA-MP-A4TK-01,0.263208,4.657474,0.049365,-0.334572,0.156422,-0.03171,0.102906,0.678354,0.890401,1.982928,...,0.827022,-1.006717,0.851867,2.02831,0.032823,1.222714,0.671573,-0.189095,1.195667,0.272688

In [20]:
gene.loc['TCGA-MN-A4N4-01'][['LCK', 'BCL2']].tolist()

[0.774329496684, -1.70353560671]

In [6]:
path = '/Users/hanruchen/Desktop/BioInfo_LAB/Multi_omics/data/protein_expression/TCGA-LUAD'

In [26]:
with open('protein_expression_RPPA_org.csv', 'w') as f:
    writer = csv.writer(f)
    writer.writerow(['sample_ID'] + df['peptide_target'].tolist())
    for f in os.listdir(path):
        if os.path.isdir(os.path.join(path, f)):
            for file in os.listdir(os.path.join(path, f)):
                if file[-4:] == '.tsv':
                    sample_ID = file[:16]
                    df = pd.read_table(os.path.join(path, f, file))
                    writer.writerow([sample_ID] + df['protein_expression'].tolist())

In [2]:
df = pd.read_table('/Users/hanruchen/Desktop/BioInfo_LAB/Multi_omics/data/protein_expression/TCGA-LUAD/0c8f308b-e636-45bd-9f3a-bd4e4f9d0e5c/TCGA-73-4659-01A-21-2190-20_RPPA_data.tsv')

In [3]:
df

,AGID,lab_id,catalog_number,set_id,peptide_target,protein_expression
0,AGID00100,882,sc-628,Old,1433BETA,0.039362
1,AGID00111,913,sc-23957,Old,1433EPSILON,-0.196430
2,AGID00101,883,sc-1019,Old,1433ZETA,0.000557
3,AGID00001,2,9452,Old,4EBP1,-0.557850
4,AGID00002,3,9456,Old,4EBP1_pS65,-0.248820
...,...,...,...,...,...,...
482,AGID00095,835,2900,Old,YB1_pS102,0.171100
483,AGID02217,2579,ab220163,Set165,YTHDF2,-1.017032
484,AGID02210,2572,ab220161,Set165,YTHDF3,-0.836773
485,AGID00326,1828,2705,Set165,ZAP-70,-0.189563
486,AGID00432,2244,sc-25388,Set165,ZEB1,0.343978

In [1]:
import pandas as pd

In [4]:
df = pd.read_table('./TCGA.LUAD.sampleMap_RPPA_RBN', index_col='Sample_description')

In [6]:
df.to_csv('TCGA-LUAD_protein_expression_data.csv')